name: Generate Snake Animation

on:
  # Her gün saat 00:00'da otomatik çalıştır
  schedule:
    - cron: "0 0 * * *"

  # Manuel çalıştırmaya izin verir
  workflow_dispatch:

  # main dalına yapılan her push'ta çalıştır
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Reposunu ve .git klasörünü çek
      - name: Checkout repository content
        uses: actions/checkout@v3

      # SVG animasyonu oluştur
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: OguzIronCode
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Çıktıları output branch'ine push et
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
